server:
  test: http://127.0.0.1:8888/api/private/v1/
  # 实例代码使用的接口服务，已改为作者是自己的云服务器部署。（后端源码来自b站：https://www.bilibili.com/video/BV1EE411B7SU?p=10）
  dev: http://49.232.203.244:8888/api/private/v1/

# 实际响应jsonpath提取规则设置
response_reg:
  # 提取token的jsonpath表达式
  token: $.data.token
  # 提取实际响应的断言数据jsonpath表达式，与excel中预期结果的数据进行比对用
  response: $.meta

file_path:
  case_data: ../data/case_data.xlsx
  report_data: ../report/data/
  report_generate: ../report/html/
  report_zip: ../report/html/apiAutoTestReport.zip
  log_path: ../log/运行日志{time}.log

email:
  # 发件人邮箱
  user:  123456.com
  # 发件人邮箱授权码
  password:  ASGCSFSGS
  # 邮箱host
  host:  smtp.163.com
  contents:  解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  # 收件人邮箱
  addressees:  ["收件人邮箱1","收件人邮箱2","收件人邮箱3"]
  title:  接口自动化测试报告(见附件)
  # 附件地址
  enclosures: ["../report/html/apiAutoTestReport.zip",]

